package com.cibook.bookingticket.service;

import com.cibook.bookingticket.model.Coupon;
import com.cibook.bookingticket.repository.CouponRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
public class CouponService implements IService<Coupon, String>{
    private final CouponRepository couponRepository;
    private final AutoGeneratedCode codeGenerator;
    @Autowired
    public CouponService(CouponRepository couponRepository, AutoGeneratedCode codeGenerator) {
        this.couponRepository = couponRepository;
        this.codeGenerator = codeGenerator;
    }

    @Override
    public Coupon add(Coupon entity) {
        return couponRepository.save(entity);
    }

    @Override
    public Optional<Coupon> findById(String id) {
        return couponRepository.findById(id);
    }

    @Override
    public Optional<Coupon> findByCode(String id) {
        return couponRepository.findByCouponCode(id);
    }

    @Override
    public List<Coupon> findAll() {
        return couponRepository.findAll();
    }

    @Override
    public Map<String, String> findAllNamesWithID() {
        return null;
    }

    @Override
    public Coupon update(String id, Coupon entity) {
        if (!existsById(id)) return null;
        Coupon coupon = couponRepository.findById(id).get();
        entity.setCouponCode(coupon.getCouponCode());
        entity.setId(coupon.getId());
        return couponRepository.save(entity);
    }

    @Override
    public void deleteById(String id) {
        couponRepository.deleteById(id);
    }

    @Override
    public boolean existsById(String id) {
        return couponRepository.existsById(id);
    }
}
