package com.cibook.bookingticket.service;

import com.cibook.bookingticket.config.MongoConfig;
import com.cibook.bookingticket.model.Movie;
import com.cibook.bookingticket.repository.MovieRepository;

import org.bson.Document;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.data.mongodb.core.MongoTemplate;
import org.springframework.data.mongodb.core.query.Criteria;
import org.springframework.data.mongodb.core.query.Query;
import org.springframework.stereotype.Service;
import org.webjars.NotFoundException;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Collectors;

@Service
public class MovieService implements IService<Movie, String> {

    private final MovieRepository movieRepository;
    private final AutoGeneratedCode codeGenerator;
    private final MongoTemplate mongoTemplate;

    @Autowired
    public MovieService(MovieRepository movieRepository, AutoGeneratedCode codeGenerator, MongoTemplate mongoTemplate) {
        this.movieRepository = movieRepository;
        this.codeGenerator = codeGenerator;
        this.mongoTemplate = mongoTemplate;
    }

    @Override
    public Movie add(Movie entity) {
        entity.setMovieCode(codeGenerator.generateMovieCode());
        return movieRepository.save(entity);
    }

    @Override
    public Optional<Movie> findById(String id) {
        return movieRepository.findById(id);
    }

    @Override
    public Optional<Movie> findByCode(String id) {
        return movieRepository.findByMovieCode(id);
    }

    @Override
    public List<Movie> findAll() {
        return movieRepository.findAll().stream()
                .map(this::normalizeMovieStatus)
                .collect(Collectors.toList());
    }

    @Override
    public Page<Movie> findAll(Pageable pageable) {
        return movieRepository.findAll(pageable);
    }

    public Page<Movie> findAllWithOwner(Pageable pageable, String owner, String status, String title) {
        Query query = new Query();
        if (owner != null && !owner.trim().isEmpty()) {
            query.addCriteria(Criteria.where("owner").regex(owner, "i"));
        }
        if (status != null && !status.trim().isEmpty()) {
            query.addCriteria(Criteria.where("status").regex(status, "i"));
        }
        if (title != null && !title.trim().isEmpty()) {
            query.addCriteria(Criteria.where("title").regex(".*" + title + ".*", "i"));
        }
        query.with(pageable);
        List<Movie> results = mongoTemplate.find(query, Movie.class);
        long count = mongoTemplate.count(query.skip(-1).limit(-1), Movie.class);
        return new PageImpl<>(results, pageable, count);
    }

    private Movie normalizeMovieStatus(Movie movie) {
        if (movie.getStatus() != null) {
            String normalizedStatus = movie.getStatus();
            switch (normalizedStatus) {
                case "ended":
                    movie.setStatus("ENDED");
                    break;
                case "comming soon":
                    movie.setStatus("COMMING_SOON");
                    break;
                case "now showing":
                    movie.setStatus("NOW_SHOWING");
                    break;
                default:
                    break;
            }
        }
        return movieRepository.save(movie);
    }

    @Override
    public Map<String, String> findAllNamesWithID() {
        return findAll().stream().filter(movie -> movie.getMovieCode() != null)
                .collect(Collectors.toMap(Movie::getMovieCode, Movie::getTitle, (o1, o2) -> o2));
    }

    @Override
    public Movie update(String id, Movie entity) {
        if (!existsById(id))
            return null;
        Movie movie = movieRepository.findById(id).get();
        entity.setMovieCode(movie.getMovieCode());
        entity.setId(movie.getId());
        return movieRepository.save(entity);
    }

    @Override
    public void deleteById(String id) {
        movieRepository.deleteById(id);
    }

    @Override
    public boolean existsById(String id) {
        return movieRepository.existsById(id);
    }

    public Integer getDurationByMovieCode(String code) {
        Query query = new Query();
        query.addCriteria(Criteria.where("movieCode").is(code));
        query.fields().include("duration").exclude("_id");
        Document result = mongoTemplate.findOne(query, Document.class, "movies");
        return result.getInteger("duration", 0);
    }

    public void updateStatus(String id, String string) {
        Movie movie = findById(id).orElseThrow(() -> new NotFoundException("Movie not found with ID: " + id));
        movie.setStatus(string);
        movieRepository.save(movie);
    }
}
