package com.cibook.bookingticket.service;

import com.cibook.bookingticket.model.Showtime;
import com.cibook.bookingticket.repository.ShowtimeRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.Optional;
@Service
public class ShowtimeService implements IService<Showtime, String> {
    private final ShowtimeRepository showtimeRepository;
    private final AutoGeneratedCode codeGenerator;

    @Autowired
    public ShowtimeService(ShowtimeRepository showtimeRepository, AutoGeneratedCode codeGenerator) {
        this.showtimeRepository = showtimeRepository;
        this.codeGenerator = codeGenerator;
    }

    @Override
    public Showtime add(Showtime entity) {
        entity.setShowTimeCode(codeGenerator.generateShowtimeCode());
        return showtimeRepository.save(entity);
    }

    @Override
    public Optional<Showtime> findById(String id) {
        return showtimeRepository.findById(id);
    }

    @Override
    public Optional<Showtime> findByCode(String id) {
        return showtimeRepository.findByShowTimeCode(id);
    }

    @Override
    public List<Showtime> findAll() {
        return showtimeRepository.findAll();
    }

    @Override
    public Page<Showtime> findAll(Pageable pageable) {
        return showtimeRepository.findAll(pageable);
    }

    @Override
    public Map<String, String> findAllNamesWithID() {
        return null;
    }

    @Override
    public Showtime update(String id, Showtime entity) {
        if (!existsById(id)) return null;
        Showtime showtime = showtimeRepository.findById(id).get();
        entity.setId(id);
        entity.setShowTimeCode(showtime.getShowTimeCode());
        return showtimeRepository.save(entity);
    }

    @Override
    public void deleteById(String id) {
        showtimeRepository.deleteById(id);
    }

    @Override
    public boolean existsById(String id) {
        return showtimeRepository.existsById(id);
    }
}
