GET http://localhost:8080/api/cinemas

###

POST http://localhost:8080/api/cinemas
Content-Type: application/json
{
    "cinemaName": "CGV NVL",
    "location": "1058 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
    "numberOfScreens": 20,
    "owner": "CGV",
    "status": "OPEN"
}

###
GET http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f

###
PUT http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f
Content-Type: application/json
{
    "cinemaName": CGV,
    "location": "1058 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
    "numberOfScreens": 200,
    "owner": CGV,
    "status": "OPEN"
}

###
DELETE http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f

###
GET http://localhost:8080/api/cinemas/names

##### SCREEN

GET http://localhost:8080/api/screens

###

POST http://localhost:8080/api/screens
Content-Type: application/json

{
    "type": "IMAX",
    "capacity": 120,
    "status": "Inactive",
    "cinemaId": "CIN002"
}

###
GET http://localhost:8080/api/screens/67ee9dd530e5a56c36c9887b
Content-Type: application/json


###
PUT http://localhost:8080/api/screens/67ee9f8a8b107902ad735d65
Content-Type: application/json

{
  "type": "VIP",
  "capacity": 120,
  "status": "Inactive",
  "cinemaId": "CIN002"
}

###
DELETE http://localhost:8080/api/screens/67ee9dd030e5a56c36c9887a

####
GET http://localhost:8080/api/screens/names

###
POST http://localhost:8080/api/screens/many
Content-Type: application/json

[
  {
    "type": "IMAX",
    "capacity": 200,
    "status": "Inactive",
    "cinemaId": "CIN001"
  },
  {
    "type": "3D",
    "capacity": 180,
    "status": "ACTIVE",
    "cinemaId": "CIN002"
  },
  {
    "type": "Standard",
    "capacity": 120,
    "status": "ACTIVE",
    "cinemaId": "CIN003"
  },
  {
    "type": "Deluxe",
    "capacity": 100,
    "status": "ACTIVE",
    "cinemaId": "CIN003"
  },
  {
    "type": "Standard",
    "capacity": 150,
    "status": "ACTIVE",
    "cinemaId": "CIN004"
  },
  {
    "type": "VIP",
    "capacity": 60,
    "status": "ACTIVE",
    "cinemaId": "CIN004"
  },
  {
    "type": "3D",
    "capacity": 180,
    "status": "ACTIVE",
    "cinemaId": "CIN005"
  },
  {
    "type": "4DX",
    "capacity": 90,
    "status": "ACTIVE",
    "cinemaId": "CIN005"
  },
  {
    "type": "IMAX",
    "capacity": 220,
    "status": "ACTIVE",
    "cinemaId": "CIN001"
  },
  {
    "type": "Deluxe",
    "capacity": 130,
    "status": "ACTIVE",
    "cinemaId": "CIN001"
  },
  {
    "type": "Standard",
    "capacity": 140,
    "status": "INACTIVE",
    "cinemaId": "CIN002"
  },
  {
    "type": "VIP",
    "capacity": 90,
    "status": "ACTIVE",
    "cinemaId": "CIN002"
  },
  {
    "type": "3D",
    "capacity": 160,
    "status": "UNDER_MAINTENANCE",
    "cinemaId": "CIN003"
  },
  {
    "type": "IMAX",
    "capacity": 200,
    "status": "ACTIVE",
    "cinemaId": "CIN003"
  },
  {
    "type": "Deluxe",
    "capacity": 110,
    "status": "ACTIVE",
    "cinemaId": "CIN004"
  },
  {
    "type": "Standard",
    "capacity": 150,
    "status": "INACTIVE",
    "cinemaId": "CIN004"
  },
  {
    "type": "4DX",
    "capacity": 100,
    "status": "ACTIVE",
    "cinemaId": "CIN005"
  },
  {
    "type": "VIP",
    "capacity": 120,
    "status": "ACTIVE",
    "cinemaId": "CIN005"
  },
  {
    "type": "IMAX",
    "capacity": 180,
    "status": "ACTIVE",
    "cinemaId": "CIN002"
  },
  {
    "type": "3D",
    "capacity": 150,
    "status": "ACTIVE",
    "cinemaId": "CIN001"
  }
]



###
DELETE http://localhost:8080/api/screens/many


### SEATS
GET http://localhost:8080/api/seats

###
POST http://localhost:8080/api/seats
Content-Type: application/json

{
  "number": "01",
  "type": "Couple",
  "row": "H",
  "screenCode": "SCR001",
  "cinemaCode": "CI001",
  "multiplier": 1.0,
  "status": "AVAILABLE"
}

###
GET http://localhost:8080/api/seats/67eead2837c02c5cd1371caf


###
PUT http://localhost:8080/api/seats/67eead2837c02c5cd1371caf
Content-Type: application/json

{
  "seatCode": "A02",
  "number": "02",
  "type": "Couple",
  "row": "H",
  "screenCode": "SCR001",
  "cinemaCode": "CI001",
  "multiplier": 2.0,
  "status": "AVAILABLE"
}

###
POST http://localhost:8080/api/seats/all
Content-Type: application/json

[
  { "seatCode": "S001", "number": "1", "type": "Standard", "row": "A", "screenCode": "SCR001", "cinemaCode": "CIN001", "status": "AVAILABLE" },
  { "seatCode": "S002", "number": "2", "type": "VIP", "row": "B", "screenCode": "SCR002", "cinemaCode": "CIN002", "status": "BOOKED" },
  { "seatCode": "S003", "number": "3", "type": "Couple", "row": "C", "screenCode": "SCR003", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S004", "number": "4", "type": "Standard", "row": "D", "screenCode": "SCR004", "cinemaCode": "CIN004", "status": "MAINTENANCE" },
  { "seatCode": "S005", "number": "5", "type": "VIP", "row": "E", "screenCode": "SCR001", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S006", "number": "6", "type": "Standard", "row": "F", "screenCode": "SCR002", "cinemaCode": "CIN001", "status": "BOOKED" },
  { "seatCode": "S007", "number": "7", "type": "VIP", "row": "G", "screenCode": "SCR003", "cinemaCode": "CIN002", "status": "AVAILABLE" },
  { "seatCode": "S008", "number": "8", "type": "Couple", "row": "H", "screenCode": "SCR004", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S009", "number": "9", "type": "Standard", "row": "I", "screenCode": "SCR001", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S010", "number": "10", "type": "VIP", "row": "J", "screenCode": "SCR002", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S011", "number": "11", "type": "Standard", "row": "A", "screenCode": "SCR003", "cinemaCode": "CIN001", "status": "AVAILABLE" },
  { "seatCode": "S012", "number": "12", "type": "VIP", "row": "B", "screenCode": "SCR004", "cinemaCode": "CIN002", "status": "MAINTENANCE" },
  { "seatCode": "S013", "number": "13", "type": "Couple", "row": "C", "screenCode": "SCR001", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S014", "number": "14", "type": "Standard", "row": "D", "screenCode": "SCR002", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S015", "number": "15", "type": "VIP", "row": "E", "screenCode": "SCR003", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S016", "number": "16", "type": "Standard", "row": "F", "screenCode": "SCR004", "cinemaCode": "CIN001", "status": "MAINTENANCE" },
  { "seatCode": "S017", "number": "17", "type": "VIP", "row": "G", "screenCode": "SCR001", "cinemaCode": "CIN002", "status": "AVAILABLE" },
  { "seatCode": "S018", "number": "18", "type": "Couple", "row": "H", "screenCode": "SCR002", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S019", "number": "19", "type": "Standard", "row": "I", "screenCode": "SCR003", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S020", "number": "20", "type": "VIP", "row": "J", "screenCode": "SCR004", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S021", "number": "21", "type": "Standard", "row": "A", "screenCode": "SCR001", "cinemaCode": "CIN001", "status": "AVAILABLE" },
  { "seatCode": "S022", "number": "22", "type": "VIP", "row": "B", "screenCode": "SCR002", "cinemaCode": "CIN002", "status": "MAINTENANCE" },
  { "seatCode": "S023", "number": "23", "type": "Couple", "row": "C", "screenCode": "SCR003", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S024", "number": "24", "type": "Standard", "row": "D", "screenCode": "SCR004", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S025", "number": "25", "type": "VIP", "row": "E", "screenCode": "SCR001", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S026", "number": "26", "type": "Standard", "row": "F", "screenCode": "SCR002", "cinemaCode": "CIN001", "status": "MAINTENANCE" },
  { "seatCode": "S027", "number": "27", "type": "VIP", "row": "G", "screenCode": "SCR003", "cinemaCode": "CIN002", "status": "AVAILABLE" },
  { "seatCode": "S028", "number": "28", "type": "Couple", "row": "H", "screenCode": "SCR004", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S029", "number": "29", "type": "Standard", "row": "I", "screenCode": "SCR001", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S030", "number": "30", "type": "VIP", "row": "J", "screenCode": "SCR002", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S031", "number": "31", "type": "Standard", "row": "A", "screenCode": "SCR003", "cinemaCode": "CIN001", "status": "AVAILABLE" },
  { "seatCode": "S032", "number": "32", "type": "VIP", "row": "B", "screenCode": "SCR004", "cinemaCode": "CIN002", "status": "MAINTENANCE" },
  { "seatCode": "S033", "number": "33", "type": "Couple", "row": "C", "screenCode": "SCR001", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S034", "number": "34", "type": "Standard", "row": "D", "screenCode": "SCR002", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S035", "number": "35", "type": "VIP", "row": "E", "screenCode": "SCR003", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S036", "number": "36", "type": "Standard", "row": "F", "screenCode": "SCR004", "cinemaCode": "CIN001", "status": "MAINTENANCE" },
  { "seatCode": "S037", "number": "37", "type": "VIP", "row": "G", "screenCode": "SCR001", "cinemaCode": "CIN002", "status": "AVAILABLE" },
  { "seatCode": "S038", "number": "38", "type": "Couple", "row": "H", "screenCode": "SCR002", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S039", "number": "39", "type": "Standard", "row": "I", "screenCode": "SCR003", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S040", "number": "40", "type": "VIP", "row": "J", "screenCode": "SCR004", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S041", "number": "41", "type": "Standard", "row": "A", "screenCode": "SCR001", "cinemaCode": "CIN001", "status": "AVAILABLE" },
  { "seatCode": "S042", "number": "42", "type": "VIP", "row": "B", "screenCode": "SCR002", "cinemaCode": "CIN002", "status": "MAINTENANCE" },
  { "seatCode": "S043", "number": "43", "type": "Couple", "row": "C", "screenCode": "SCR003", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S044", "number": "44", "type": "Standard", "row": "D", "screenCode": "SCR004", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S045", "number": "45", "type": "VIP", "row": "E", "screenCode": "SCR001", "cinemaCode": "CIN005", "status": "AVAILABLE" },
  { "seatCode": "S046", "number": "46", "type": "Standard", "row": "F", "screenCode": "SCR002", "cinemaCode": "CIN001", "status": "MAINTENANCE" },
  { "seatCode": "S047", "number": "47", "type": "VIP", "row": "G", "screenCode": "SCR003", "cinemaCode": "CIN002", "status": "AVAILABLE" },
  { "seatCode": "S048", "number": "48", "type": "Couple", "row": "H", "screenCode": "SCR004", "cinemaCode": "CIN003", "status": "AVAILABLE" },
  { "seatCode": "S049", "number": "49", "type": "Standard", "row": "I", "screenCode": "SCR001", "cinemaCode": "CIN004", "status": "BOOKED" },
  { "seatCode": "S050", "number": "50", "type": "VIP", "row": "J", "screenCode": "SCR002", "cinemaCode": "CIN005", "status": "AVAILABLE" }
]


###
DELETE http://localhost:8080/api/seats/all

### MOVIES
GET http://localhost:8080/api/movies

###
GET http://localhost:8080/api/movies/67eeb346e21d8829e5c0d4a6

###
PUT http://localhost:8080/api/movies/67eeb346e21d8829e5c0d4a6
Content-Type: application/json

{
  "movieCode": "MOV010",
  "thumbnail": "https://image.tmdb.org/t/p/w200/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
  "title": "Dune: Part Two",
  "genre": [
    "Sci-Fi"
  ],
  "releaseYear": 2024,
  "director": "Denis Villeneuve",
  "rating": 2.0,
  "duration": 165,
  "language": "English",
  "budget": 1.9E8,
  "boxOffice": null,
  "casts": [
    "Timothée Chalamet",
    "Zendaya",
    "Rebecca Ferguson"
  ],
  "releasedBy": "Galaxy Cinema",
  "releaseDate": "2024-03-15T00:00:00Z",
  "endDate": "2024-06-20T00:00:00Z",
  "trailer": "hiii",
  "description": "",
  "status": "COMING_SOON"
}

###
GET http://localhost:8080/api/movies/code/MOV001


###Coupon
GET http://localhost:8080/api/coupons