GET http://localhost:8080/api/cinemas

###

POST http://localhost:8080/api/cinemas
Content-Type: application/json
{
    "cinemaName": "CGV NVL",
    "location": "1058 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
    "numberOfScreens": 20,
    "owner": "CGV",
    "status": "OPEN"
}

###
GET http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f

###
PUT http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f
Content-Type: application/json
{
    "cinemaName": CGV,
    "location": "1058 Nguyễn Văn Linh, Tân Phong, Quận 7, TP.HCM",
    "numberOfScreens": 200,
    "owner": CGV,
    "status": "OPEN"
}

###
DELETE http://localhost:8080/api/cinemas/67ec2caee21d8829e5c0d28f

###
GET http://localhost:8080/api/cinemas/names

##### SCREEN

GET http://localhost:8080/api/screens

###

POST http://localhost:8080/api/screens
Content-Type: application/json

{
    "type": "IMAX",
    "capacity": 120,
    "status": "Inactive",
    "cinemaId": "CIN002"
}

###
GET http://localhost:8080/api/screens/67ee9dd530e5a56c36c9887b
Content-Type: application/json


###
PUT http://localhost:8080/api/screens/67ee9f8a8b107902ad735d65
Content-Type: application/json

{
  "type": "VIP",
  "capacity": 120,
  "status": "Inactive",
  "cinemaId": "CIN002"
}

###
DELETE http://localhost:8080/api/screens/67ee9dd030e5a56c36c9887a

####
GET http://localhost:8080/api/screens/names


### SEATS
GET http://localhost:8080/api/seats

###
POST http://localhost:8080/api/seats
Content-Type: application/json

{
  "number": "01",
  "type": "Couple",
  "row": "H",
  "screenCode": "SCR001",
  "cinemaCode": "CI001",
  "multiplier": 1.0,
  "status": "AVAILABLE"
}

###
GET http://localhost:8080/api/seats/67eead2837c02c5cd1371caf


###
PUT http://localhost:8080/api/seats/67eead2837c02c5cd1371caf
Content-Type: application/json

{
  "seatCode": "A02",
  "number": "02",
  "type": "Couple",
  "row": "H",
  "screenCode": "SCR001",
  "cinemaCode": "CI001",
  "multiplier": 2.0,
  "status": "AVAILABLE"
}

### MOVIES
GET http://localhost:8080/api/movies

###
GET http://localhost:8080/api/movies/67eeb346e21d8829e5c0d4a6

###
PUT http://localhost:8080/api/movies/67eeb346e21d8829e5c0d4a6
Content-Type: application/json

{
  "movieCode": "MOV010",
  "thumbnail": "https://image.tmdb.org/t/p/w200/8pjWz2lt29KyVGoq1mXYu6Br7dE.jpg",
  "title": "Dune: Part Two",
  "genre": [
    "Sci-Fi"
  ],
  "releaseYear": 2024,
  "director": "Denis Villeneuve",
  "rating": 2.0,
  "duration": 165,
  "language": "English",
  "budget": 1.9E8,
  "boxOffice": null,
  "casts": [
    "Timothée Chalamet",
    "Zendaya",
    "Rebecca Ferguson"
  ],
  "releasedBy": "Galaxy Cinema",
  "releaseDate": "2024-03-15T00:00:00Z",
  "endDate": "2024-06-20T00:00:00Z",
  "trailer": "hiii",
  "description": "",
  "status": "COMING_SOON"
}

###
GET http://localhost:8080/api/movies/code/MOV001


###Coupon
GET http://localhost:8080/api/coupons